### ISSUE TITLE
A request to add a citation to our work

### ISSUE THREAD

**Issue by hyx1999** [kriskrisliu/PAT_Pruning-Aware-Tuning#1]
Hello, I am a current PhD student from Renmin University of China, also working on model pruning. Congratulations on such good results with your work! 

In the last year, we also proposed an approach to width pruning, similar to SliceGPT, but so far no one has paid attention to our work. So, could you please cite our work? I would be grateful if you could possibly reference our work in your studies. :sob: We'll be following up on your work!

[https://arxiv.org/abs/2308.16475](url)

**Comment by kriskrisliu** [comment]
Very interesting paper, and we will include it in our references in the next revision.
